import type { Metadata } from 'next'
import '@/assets/styles/globals.scss'
import Header from '@/widgets/header/ui/Header'
import CustomProvider from '@/features/provider/CustomProvider'
import Footer from '@/widgets/footer/Footer'

export const metadata: Metadata = {
	title: 'Poland24',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				<CustomProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</CustomProvider>
			</body>
		</html>
	)
}
